adding obi2ahb gasket
openhwgroup/cve2 pull request #160
Opened 2023-09-29 18:45 UTC by LeeHoff

source file obi2ahb_adapter.sv and initial design spec "OBI2AHMB_Adapter Design Spec.pdf"

2023-10-03 15:24 UTC, MikeOpenHWGroup commented
Thanks for this @LeeHoff!  Can we get a version of the documentation with an Apache/Solderpad license header added?

2023-10-05 13:31 UTC, christian-herber-nxp commented
I can't really be a reviewer for the RTL. However, I would question if this should be in a folder called example. This suggests to me at most TRL2-3. In my understanding, the gasket should be at the same quality level as the rest.

2023-10-05 13:33 UTC, christian-herber-nxp commented on examples/obi2ahb/obi2ahbm_adapter.sv
> +   input  logic           priv_mode       // (I) Privilege mode (from core)
maybe add the definition of the signal here, i.e. what does 0 mean and what does 1 mean

2023-10-10 18:09 UTC, LeeHoff commented on examples/obi2ahb/obi2ahbm_adapter.sv
> +   input  logic           priv_mode       // (I) Privilege mode (from core)
I added the description of what 1 vs. 0 means in the new file.

2023-10-10 18:09 UTC, LeeHoff commented
Correcting the copywrite string.

2023-10-10 18:12 UTC, MikeOpenHWGroup approved these changes

2023-10-10 18:12 UTC, MikeOpenHWGroup commented on examples/obi2ahb/obi2ahbm_adapter.sv
> +   input  logic           priv_mode       // (I) Privilege mode (from core)
Thanks!

2023-10-10 18:14 UTC, MikeOpenHWGroup commented
LGTM @LeeHoff, thanks for the update.  I have approved this PR, so legally it is good-to-merge, but I will defer to either yourself or @davideschiavone to execute.   Thanks for this contribution!

2023-10-10 19:35 UTC, davideschiavone commented
@LeeHoff , @christian-herber-nxp , @joecircello , before digging into the RTL review, a question/suggestion from my side, wouldn't it be better to have this in a separate repository so that it can be used by any OBI master?

2023-10-10 19:56 UTC, MikeOpenHWGroup commented
> wouldn't it be better to have this in a separate repository so that it can be used by any OBI master?

It was suggested that we should get this specific component into an OpenHW repo first and worry about the creation of a library repo at a later date. 

While one could argue that we _should_ have a repo for a library of reuseable RTL components, we currently do not and we can always move this component at a later date.

2023-10-10 20:05 UTC, davideschiavone requested changes

2023-10-10 20:05 UTC, davideschiavone commented on examples/obi2ahb/obi2ahbm_adapter.sv
> +   output logic  [31:0]   haddr_m,        // (O) 32-bit AHB system address bus
please, use _o for output logic signals and _i for input logic signals in the AHB master interface.

We can also get rid of the "m" as the "master" should be in the module name - something like "obi2ahb_master"

2023-10-10 20:05 UTC, davideschiavone commented on examples/obi2ahb/obi2ahbm_adapter.sv
> +   input  logic           data_req_o,     // (I) Request ready
similarly, data_req_o is an input, and should be _i

2023-10-10 20:05 UTC, davideschiavone commented on examples/obi2ahb/obi2ahbm_adapter.sv
> +   always @ (*) begin
this looks more Verilog than Systemverilog, although legal, maybe a simple assign would be good?

2023-10-10 20:05 UTC, davideschiavone commented on examples/obi2ahb/obi2ahbm_adapter.sv
> +   always @ (*) begin
please use always_comb

2023-10-10 20:05 UTC, davideschiavone commented on examples/obi2ahb/obi2ahbm_adapter.sv
> +      endcase
please add a default case, often asked for having lint errors free code

2023-10-10 20:05 UTC, davideschiavone commented on examples/obi2ahb/obi2ahbm_adapter.sv
> +   always @ (*) begin
please use always_comb

2023-10-10 20:05 UTC, davideschiavone commented on examples/obi2ahb/obi2ahbm_adapter.sv
> +    endcase
please add default statement

2023-10-10 20:09 UTC, davideschiavone requested changes

2023-10-10 20:09 UTC, davideschiavone commented on examples/obi2ahb/obi2ahbm_adapter.sv
> +// Description    : OBI to AHB-Lite Master Adaptor
I guess we should also write which version of OBI and which version of AHB-Lite we are referring to

2023-12-11 21:14 UTC, LeeHoff commented on examples/obi2ahb/obi2ahbm_adapter.sv
> +// Description    : OBI to AHB-Lite Master Adaptor
I have added a comment that states the versions of OBI and AHB that we have targeted.

2023-12-11 21:14 UTC, LeeHoff commented on examples/obi2ahb/obi2ahbm_adapter.sv
> +      endcase
I added default case statements.

2023-12-11 21:15 UTC, LeeHoff commented on examples/obi2ahb/obi2ahbm_adapter.sv
> +    endcase
I added a default case statement.

2023-12-11 21:16 UTC, LeeHoff commented on examples/obi2ahb/obi2ahbm_adapter.sv
> +   output logic  [31:0]   haddr_m,        // (O) 32-bit AHB system address bus
I have renamed the I/O logic signals to have the appropriate _o or _i appended to the signal names.

2023-12-11 21:17 UTC, LeeHoff commented on examples/obi2ahb/obi2ahbm_adapter.sv
> +   always @ (*) begin
I changed this into an assign statement.

2023-12-11 21:18 UTC, LeeHoff commented on examples/obi2ahb/obi2ahbm_adapter.sv
> +   input  logic           data_req_o,     // (I) Request ready
I have renamed the I/O logic signals to have the appropriate _o or _i appended to the signal names.

2023-12-12 07:31 UTC, davideschiavone approved these changes

2023-12-12 07:31 UTC, merged