RVFI CSRs tracing
openhwgroup/cve2 pull request #184
Opened 2024-02-26 11:17 UTC by MarioOpenHWGroup

Implementation of RVFI CSRs. 

This supposes that the testbench binds a `rvfi_unified_csr_if` in the `cs_registers.sv` module.

2024-02-26 11:24 UTC, davideschiavone requested changes

2024-02-26 11:24 UTC, davideschiavone commented on rtl/cve2_cs_registers.sv
> +import cve2_pkg::*;
can you move this after the module declaration? 

```

`include "prim_assert.sv"

module cve2_cs_registers #(
  parameter bit               DbgTriggerEn      = 0,
  parameter int unsigned      DbgHwBreakNum     = 1,
  parameter int unsigned      MHPMCounterNum    = 10,
  parameter int unsigned      MHPMCounterWidth  = 40,
  parameter bit               PMPEnable         = 0,
  parameter int unsigned      PMPGranularity    = 0,
  parameter int unsigned      PMPNumRegions     = 4,
  parameter bit               RV32E             = 0,
  parameter cve2_pkg::rv32m_e RV32M             = cve2_pkg::RV32MFast,
  parameter cve2_pkg::rv32b_e RV32B             = cve2_pkg::RV32BNone
) (
  // Clock and Reset
  input  logic                 clk_i,
  input  logic                 rst_ni,
....
 input  logic                 wfi_wait_i,                  // core waiting for interrupt
  input  logic                 div_wait_i                   // core waiting for divide
);

  import cve2_pkg::*;
```

2024-02-26 12:05 UTC, davideschiavone approved these changes

2024-02-26 12:05 UTC, merged

2024-05-28 08:44 UTC, ilamparithy01 commented on rtl/cve2_cs_registers.sv
> +import cve2_pkg::*;
Hi I am started to use this comit, I a unable to compile the design , It is throwing error in cve2_cs_register 
where traces is added 
Error found while trying to resolve cross-module reference.
  token 'clknrst_if'.  Originating module 'cve2_cs_registers' like this

2024-05-28 11:24 UTC, MarioOpenHWGroup commented on rtl/cve2_cs_registers.sv
> +import cve2_pkg::*;
This has to be used with the new cv32e20-dv repo as this has the bind interfaces

2024-05-28 12:26 UTC, MikeOpenHWGroup commented on rtl/cve2_cs_registers.sv
> +import cve2_pkg::*;
See #271 for additional discussion on this point.

2024-05-29 06:03 UTC, ilamparithy01 commented on rtl/cve2_cs_registers.sv
> +import cve2_pkg::*;
@MarioOpenHWGroup 
I am not seeing anything in cv32e20 -dv , I am only seeing coming soon.
could help me out how to compile the design without error , I checked out this version.
I created allfile.txt with the help of cv32e20_manifest.flist and doing compile , do i need to add somthing to resolve the interface signals.

2024-05-29 06:13 UTC, ilamparithy01 commented on rtl/cve2_cs_registers.sv
> +import cve2_pkg::*;
my initial requirement is to fetch the data and write and read some date from memory, 
how we need to provide the address map 
I am new to this that why I am asking .